version: '1.0'

services:
  flask_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      # MAC usually already use port 5000
      - "5001:5000"
    depends_on:
      - qdrant
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:

